// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLk7gfe9fTQp8g5Zu5Appg5n-r83yPWSQ',
    appId: '1:710109481594:android:160c1691750b8cd74c49c3',
    messagingSenderId: '710109481594',
    projectId: 'testing-4ede3',
    storageBucket: 'testing-4ede3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfPE_IBiz838nPvqmt3Tdn5aVuRyNo5TY',
    appId: '1:710109481594:ios:fcd2641deae2daa14c49c3',
    messagingSenderId: '710109481594',
    projectId: 'testing-4ede3',
    storageBucket: 'testing-4ede3.appspot.com',
    androidClientId: '710109481594-lnf63ia5scgc14s7oa2foqj05b7v7mvi.apps.googleusercontent.com',
    iosClientId: '710109481594-e8epsskv0nvtfg560p8popgtf3s49mhr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
  );
}
